### ISSUE TITLE
Unicode version and NFC

### ISSUE THREAD

**Issue by djstrong** [adraffy/ensip-norm#3]
I wanted to post in https://discuss.ens.domains/t/ens-name-normalization/8652/383 but the thread is disabled/closed.

I am trying to implement the normalization algorithm (https://github.com/adraffy/ensip-norm/blob/main/draft.md) in Python. The problem is with NFC normalization, because the newest stable Python standard module (unicodedata) supports Unicode 13 and therefore some validation tests are failing. This is general problem in any language that they will be supporting Unicode few months/years after new Unicode version will be official. Some solution is to find/develop libraries providing Unicode 15 NFC.

Could you add some information to the draft about Unicode version? E.g. it should be applied with the newest Unicode version (in September 2022 for Unicode 15).

**Comment by adraffy** [comment]
I wanted to decouple the ENSIP from a [specific Unicode version](https://unicode.org/reports/tr15/#Versioning) but it does appear new combining marks will cause normalization to diverge between Unicode versions.

For example:  from [NormalizationTests for Unicode 14](https://www.unicode.org/Public/14.0.0/ucd/NormalizationTest.txt) using Python 3.9 unicodedata, `61 59A 316 1DFA 316 62` incorrectly NFC's to `61 316 59A 1DFA 316 62` as `1DFA` was added in Unicode 14.

You are correct, NFC does need versioned.  At the moment, the expectation would be Unicode 14.  

This also causes a problem for any Javascript implementation as the version of Unicode isn't exposed and must be probed through examples.

Let me see revisit this and see if an earlier version could be used if additional characters were disallowed.

---

My research branch did have some Python tests but I didn't investigate further:
https://github.com/adraffy/ens-normalize.js/blob/before-ensip/test/nf.py
https://github.com/adraffy/ens-normalize.js/blob/before-ensip/test/compare-nf.js

I originally planned to embed a pure-JS NF implementation, but I was worried about implementation complexity and file size.
https://github.com/adraffy/ens-normalize.js/blob/before-ensip/build/nf.js

**Comment by adraffy** [comment]
I implemented the following change which puts constraints on combining marks:
https://discuss.ens.domains/t/ens-name-normalization/8652/386?u=raffy

* This should greatly increase Unicode Normalization Forms support when not using Unicode 14.0.0
    * Node 12 with Unicode 11 fails 1 test
    * Node 14 with Unicode 13 fails 0 tests
* I will work on creating a wider test suite to test other NF implementations and versions
    * If this ends up being a disaster, I'll just include a NF implementation w/the spec.

I also updated the ENSIP to explicitly state the Unicode version:
https://github.com/adraffy/ensip-norm/blob/201d440b42aebd64f037a6df112e4d8d975cb5c0/draft.md#versioning

**Comment by adraffy** [comment]
The spec now requires Unicode 15 and a straight-forward implementation is included with [adraffy/ens-normalize.js](https://github.com/adraffy/ens-normalize.js/blob/main/src/nf.js)
