### ISSUE TITLE
Normalization for (Potentially) Multi-Name Lookup Operations: Begins With / Ends With / Contains

### ISSUE THREAD

**Issue by josiahadams** [adraffy/ensip-norm#4]
The current normalization assumes that all lookups are intended to be some form of an exact match lookup. Some dapps may also wish to build other forms of lookup operations, such as Begins With / Ends With / Contains. Ideally there can be a standardized way to normalize input for these types of queries too.

For example, some dapps might wish to allow a user to find all domains by queries like the following:

1. Begins With: "AbC"
2. Begins With: "AbC."
3. Begins With "AbC.DeF"
4. Ends With: "AbC"
5. Ends With: ".AbC"
6. Ends With "AbC.DeF"
7. Contains: "AbC"
8. Contains: ".AbC"
9. Contains: "AbC."
10. Contains: ".AbC."
11. Contains: "AbC.DeF"

In each case above, ideally there would be a standardized way to map from an input string to a normalized "name fragment", rather than a full normalized name.

**Comment by adraffy** [comment]
For a valid implementation, I believe the following hack is a normalized fragment:
`fragment.split('.').map(s => ens_normalize('aaa$'+s).slice(4)).join('.')`

* Emoji in a fragment must be valid.  For reference, each emoji part of a ZWJ emoji sequence (split on `200D`) is also a valid emoji.  
* Both the haystack and needle should probably be in NFD form for best results.

I can add an appendix on string functions in the next update.

For a cleaner future solution, I'll expose the internal [normalize function](https://github.com/adraffy/ens-normalize.js/blob/1571a7d226f564ac379a533a3b04a15977a0ae80/src/lib.js#L41) of `@adraffy/ens_normalize.js` which is effectively `ens_normalize_fragment()`.

**Comment by adraffy** [comment]
I added a short comment about normalized fragments to the ENSIP:
https://github.com/adraffy/ensip-norm/blob/201d440b42aebd64f037a6df112e4d8d975cb5c0/draft.md#normalized-fragments

In `@adraffy/ens_normalize.js`, I exposed `ens_normalize_fragment()`.  I included some examples which test for containment using a fragment that doesn't normalize according to the full spec:
https://github.com/adraffy/ens-normalize.js/blob/cccde58eb49c895d34d5c64ac1d26b7fe764a9f4/test/fragment.js

**Comment by adraffy** [comment]
I also exposed `ens_normalize_post_check()` which runs the positional rules on each label (underscore, adjacent combining marks, etc.)

 `ens_normalize(s) === ens_normalize_post_check(ens_normalize_fragment(s))` [source](https://github.com/adraffy/ens-normalize.js/blob/e4139d7563c63cd12a08a32cfafcc999a6c29dad/src/lib.js#L90)
