### ISSUE TITLE
Skin tones

### ISSUE THREAD

**Issue by djstrong** [adraffy/ensip-norm#5]
Skin tones (🏼) are now valid characters. So emojis with multiple skin tones are valid: 🧑🏼🏼🏼
Also many libraries treats 🧑🏼🏼🏼 as one grapheme, which is wrong IMO.

**Comment by adraffy** [comment]
Let me compute some stats on this.  

I recently changed it so single regional indicators are invalid and only valid flags are accepted.  I think a similar change could happen with skin and hair modifiers if the registrations support it.  

For reference:  the reason why singular modifiers are considered valid at the moment is that EIP-137/ENSIP-1 made no distinction.  Similar logic applies to the IDNA mapped OG Japanese emoji.

**Comment by adraffy** [comment]
https://discuss.ens.domains/t/ens-name-normalization-2/14564/7

I made some comments here.  This actually revealed an issue regarding unmodified RGI sequences + trailing modifier.

**Comment by djstrong** [comment]
Thanks for investigation.
![image](https://user-images.githubusercontent.com/1849959/193532583-2005ebfd-807e-448e-ac75-297d4753d727.png)
What spec do you refer? I think this is correct.
![image](https://user-images.githubusercontent.com/1849959/193532742-cd856a12-57df-40a6-b11a-334defba32df.png)

**Comment by adraffy** [comment]
That sequence is fine, as well as the one w/o any skin-colors.

The problem is w/o followed by a skin-color that colors only one of the people.

![image](https://user-images.githubusercontent.com/225900/193533717-dec28f67-2a48-44c0-a92a-bd41a4047890.png)

**Comment by djstrong** [comment]
It is rendered correctly on my computer:
![image](https://user-images.githubusercontent.com/1849959/193880591-38145e3e-c51b-42bd-91b9-9f53533e54db.png)
And it is not I guess:
![image](https://user-images.githubusercontent.com/1849959/193881324-aefa137e-a2f5-46fc-81f5-6414aac53d45.png)

**Comment by adraffy** [comment]
Unicode can't make up their mind: "Emoji_Modifier" are not Emoji however they are included in "Emoji_Presentation"

This was addressed here: https://discuss.ens.domains/t/ens-name-normalization-2nd/14564/10

The variants above are no longer allowed.
