### ISSUE TITLE
Include Link to Python Implementation of Standard

### ISSUE THREAD

**Issue by lightwalker-eth** [adraffy/ensip-norm#6]
There's currently a link in the readme to the Javascript implementation of the standard. It seems nice to also add a link to the Python implementation here: https://github.com/namehash/ens-normalize-python

What do you think? 😄

**Comment by adraffy** [comment]
Updated, also added to ens-normalize.js readme

FYI this repo is out of date.  Latest updates in [branch of ENS docs.](https://github.com/adraffy/ensip-15/blob/master/ens-improvement-proposals/ensip-15-normalization-standard.md)

**Comment by lightwalker-eth** [comment]
Thanks @adraffy Will mark this as closed :+1:
